info:
  description: quash API
  license:
    name: MIT
  title: quash
  version: 0.1.0
paths:
  /:
    get:
      tags:
      - info
      summary: Get a dictionary of API paths
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Root'
  /info:
    get:
      summary: Get server configuration and version information
      tags:
      - info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
  /openapi:
    get:
      summary: Get the OpenAPI specification
      tags:
      - info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi'
  /ping:
    get:
      tags:
      - info
      summary: Ping the client
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ping'
openapi: 3.0.2
components:
  schemas:
    Root:
      type: object
      properties:
        directory:
          type: array
          example:
          - /
          - /info
          - /openapi
          - /ping
          - /weather/forecast
          items:
            type: string
    Inner:
      type: object
      properties:
        machine_name:
          type: string
          example: dev-machine
        python_version:
          type: string
          example: 3.8.10
        db_version:
          type: string
          example: 10.4.22-MariaDB-1:10.4.22+maria~focal-log
        api_version:
          type: string
          example: 0.3.0
        database:
          type: string
          example: my_db
        platform:
          type: string
          example: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
      required:
      - api_version
      - database
      - db_version
      - machine_name
      - platform
      - python_version
    Info:
      type: object
      properties:
        info:
          $ref: '#/components/schemas/Inner'
    OpenApi:
      type: object
      properties:
        paths:
          type: object
        info:
          type: object
        components:
          type: object
        openapi:
          type: string
      required:
      - components
      - info
      - openapi
      - paths
    Ping:
      type: object
      properties:
        destination:
          type: string
          example: 192.168.1.77
        packet_loss_count:
          type: integer
          example: 0
        packet_transmit:
          type: integer
          example: 1
        rtt_mdev:
          type: number
          example: 0.0
        rtt_avg:
          type: number
          example: 0.016
        packet_receive:
          type: integer
          example: 1
        packet_duplicate_rate:
          type: number
          example: 0.0
        packet_loss_rate:
          type: number
          example: 0.0
        rtt_max:
          type: number
          example: 0.016
        rtt_min:
          type: number
          example: 0.016
        packet_duplicate_count:
          type: integer
          example: 0
